(require :asdf)
(push *default-pathname-defaults* asdf:*central-registry*)
(asdf:load-system "web-skeleton-tests")
(handler-case (asdf:load-system "web-skeleton-tls")
  (error (e) (format t "Note: TLS not loaded (~a)~%" e)))
(unless (web-skeleton-tests:test)
  (sb-ext:exit :code 1))
